### ISSUE TITLE
[Request] Add Vietnamese stop words

### ISSUE THREAD

**Issue by Looooong** [jekyll/classifier-reborn#108]
Can you add [Vietnamese stop words](https://github.com/stopwords/vietnamese-stopwords/blob/master/vietnamese-stopwords.txt), please?

**Comment by Ch4s3** [comment]
I'd be happy to do that later. You're also welcome to put in a pr. You just need to add file called `vi` to `classifier-reborn/tree/master/data/stopwords` and paste in those stop words.
