### ISSUE TITLE
uninitialized constant ClassifierReborn::BayesRedisBackend

### ISSUE THREAD

**Issue by micmmakarov** [jekyll/classifier-reborn#109]
When trying to connect redis backend.
redis_backend = ClassifierReborn::BayesRedisBackend.new {host: "10.0.1.1", port: 6380, db: 15}

(version 2.1.0)

**Comment by micmmakarov** [comment]
![image](https://cloud.githubusercontent.com/assets/1222527/21831215/fb72c2e0-d756-11e6-9fb4-c320a3be34b9.png)

**Comment by Ch4s3** [comment]
So I should add a note that the readme on master is specific to master, 2.1.0 doesn't include the `BayesRedisBackend`. The readme for 2.1.0 is [here](https://github.com/jekyll/classifier-reborn/tree/v2.1.0). I need to better explain that in the readme. If you want to use the new backend, add `gem 'classifier-reborn', github: 'jekyll/classifier-reborn'` to your gemfile.

Let me know if that fixes the issue.

**Comment by ibnesayeed** [comment]
This suggests that although the new changes are fully backward compatible, the scope of change warrants a second point release.

**Comment by Ch4s3** [comment]
You might be right, I'll look into it a bit more!

**Comment by Ch4s3** [comment]
I'm going to do a `2.2.0` release soon

**Comment by ibnesayeed** [comment]
> @Ch4s3: I'm going to do a 2.2.0 release soon

I would suggest to wait until documentation and tests are corrected to not use the magic `method_missing` style stuff and a deprecation warning is added.

**Comment by Ch4s3** [comment]
That was the plan

**Comment by ibnesayeed** [comment]
> @Ch4s3: That was the plan

Created a ticket #140 to keep track of that.
