### ISSUE TITLE
Looks like we have classifier-reborn.com now

### ISSUE THREAD

**Issue by ibnesayeed** [jekyll/classifier-reborn#136]
@Ch4s3 looks like you were trying to put a CNAME file (that was the old way). Now, you can simply specify CNAME record in the settings. However, I think there is some issue currently as the we are hitting a 404 page when going to http://classifier-reborn.com/. I feel like it is pointing to http://jekyll.github.io/ rather than http://jekyll.github.io/classifier-reborn/.

**Comment by Ch4s3** [comment]
Yeah, I'll have to try again tomorrow. I mess it up the first time.

**Comment by ibnesayeed** [comment]
I would note here that if we don't want to give it the Jekyll branding, then it will only be appropriate to have a different favicon as well. Having said that, I am not very good at graphics so you might be able to ask someone from the design team of Jekyll to make one for the Classifier Reborn. If we become greedy, we can also ask for a logo along with the favicon.

**Comment by Ch4s3** [comment]
I'll try to handle the logo/favicon bit in the near future. 

With respect to the CNAME file, it was auto generated by github I didn't add it. Yeah I tried to point http://classifier-reborn.com/ to http://jekyll.github.io/classifier-reborn/. but the dns rejected it. The github docs seemed to suggest that github would route the request appropriately if I pointed to http://jekyll.github.io/, but it didn't.

**Comment by ibnesayeed** [comment]
In DNS records paths or protocols are not used. Project specific routing is done by GitHub internally. I am not sure why it is not working for you though. I will try something on my repos and will let you know.

**Comment by Ch4s3** [comment]
Ok, I'll poke around too

**Comment by ibnesayeed** [comment]
I was able to do it really easily. Have a look at http://classifier.metaspiders.com/

**Comment by Ch4s3** [comment]
Huh. Wonder what I'm missing. Which dns do you use?

**Comment by ibnesayeed** [comment]
Since I am using a custom subdomain, I used CNAME record in my Google Domains:

classifier => ibnesayeed.github.io.

Then I added `classifier.metaspiders.com` in my repo settings. It was up instantly.

**Comment by Ch4s3** [comment]
I'll try that again. Did you need to se the ip in an A record?

**Comment by ibnesayeed** [comment]
`A` record always needs an IP, but an `A` record is only a necessity if one tries to add Apex domain (or bare domain) and the DNS provider does not have support for `ALIAS` or `ANAME` records.

I think you can do the following in your DNS config:

```
@        A        192.30.252.153
@        A        192.30.252.154
www      CNAME    jekyll.github.io.
```

Then add `classifier-reborn.com` or `www.classifier-reborn.com` in the project's settings. I would prefer latter with `www`. This way requests without `www` will be redirected to the one with `www` automatically by GitHub.

**Comment by ibnesayeed** [comment]
> Did you need to se the ip in an A record?

No, I only added a `CNAME` record as I was only setting it up for a specific sub-domain.

**Comment by Ch4s3** [comment]
odd, it worked this time with the exact same zone file ¯\_(ツ)_/¯

**Comment by ibnesayeed** [comment]
Cool!
