### ISSUE TITLE
Making LSI evaluatable

### ISSUE THREAD

**Issue by ibnesayeed** [jekyll/classifier-reborn#144]
As per the #142 implementation, in order to evaluate a classifier, the classifier instance needs to support a uniform interface of `train`, `classify`, `categories` and `reset` methods. I have recently added `reset` functionality to all classifiers #143 as it could be useful even when not evaluated.

Is it OK if I add `train`, `classify`, `categories`, and perhaps `untrain` method as well in the LSI while internally utilizing existing methods and not breaking any backwards compatibility?

As far as I understood LSI, in order to get the list of all known categories, I will have to scan all the indexed items. Is there any other faster way to get that information?

**Comment by Ch4s3** [comment]
Yeah that should be fine

**Comment by ibnesayeed** [comment]
> @Ch4s3: Yeah that should be fine

We will take care of it in a separate PR once #142 and #143 are merged.

**Comment by Ch4s3** [comment]
You should be good to go now. Sorry to keep you waiting.
