### ISSUE TITLE
Backends not loading

### ISSUE THREAD

**Issue by lewislambert** [jekyll/classifier-reborn#160]
Hi,

I am trying to use this in a project but am unable to load the Redis Backend. I am currently using Ruby 2.3.4 and attempted to load the Redis backend in a plain IRB session.

The following output is displayed.

```
irb(main):001:0> require 'classifier-reborn'
=> true
irb(main):002:0> ClassifierReborn::Bayes
=> ClassifierReborn::Bayes
irb(main):003:0> ClassifierReborn::BayesRedisBackend
NameError: uninitialized constant ClassifierReborn::BayesRedisBackend
	from (irb):3
	from /Users/lambertl/.rbenv/versions/2.3.4/bin/irb:11:in `<main>'
irb(main):004:0> ClassifierReborn::BayesMemoryBackend
NameError: uninitialized constant ClassifierReborn::BayesMemoryBackend
	from (irb):4
	from /Users/lambertl/.rbenv/versions/2.3.4/bin/irb:11:in `<main>'
```

It seems that the `require_relative` is not actually making the classes accessible outside of the Bayes class itself, as it is able to load the memory store without issue. Has anyone else come across this problem?

Lewis

**Comment by pskarlas** [comment]
Check out  [https://github.com/jekyll/classifier-reborn/issues/109](url)  for the solution.

**Comment by tra38** [comment]
URL is broken. Try [this one](https://github.com/jekyll/classifier-reborn/issues/109).

**Comment by pskarlas** [comment]
Thanks @tra38

**Comment by Ch4s3** [comment]
@pskarlas sorry for the confusion. I need to do a new release, but I need to make sure we aren't going to break Jekyll first, and I'm a bit busy lately. I'll try to get to it soon.

**Comment by Ch4s3** [comment]
Bump. Trying to get this out soon.
