### ISSUE TITLE
RubyML list

### ISSUE THREAD

**Issue by arbox** [jekyll/classifier-reborn#163]
Dear maintainers,

we've recently added `classifier-reborn` to our RubyML list: https://github.com/arbox/machine-learning-with-ruby

In order to connect all Ruby & ML related projects we introduced the `rubyml` topic on GitHub.

Please cosider adding the `rubyml` topic to this repository as well so the Ruby community can discover `classifier-reborn` faster :smiley: 

Thank you in advance!

**Comment by Ch4s3** [comment]
Done!

**Comment by arbox** [comment]
Thank you!
