### ISSUE TITLE
Releasing 2.2.0

### ISSUE THREAD

**Issue by Ch4s3** [jekyll/classifier-reborn#164]
To the community,

I haven't had much time the last few months to work on classifier-reborn, and there's a lot of good stuff on master. I'm still hoping to make a push later this year towards 3.0, but I want to get what we have out there and make it usable. Are there any objections to a release in the next week? @ibnesayeed, @tra38, et. al.

-C

**Comment by ibnesayeed** [comment]
LGTM!

I had some enhancements planned, but I wont have spare cycles anytime soon. That said, I agree that there is a lot of good stuff and some remarkable changes that need to go out. Later we can plan an outline for 3.0 and see what changes in the architecture and the API should be made.

**Comment by parkr** [comment]
👍

**Comment by Ch4s3** [comment]
@ibnesayeed and @parkr I'll try to roll this out by the weekend. I'll also try to make sure the new version doesn't cause any jekyll issues, and put in a PR there if it looks good.

**Comment by Ch4s3** [comment]
done

**Comment by ibnesayeed** [comment]
I can see it pushed to the [RubyGems site](https://rubygems.org/gems/classifier-reborn/versions/2.2.0), but the [release](https://github.com/jekyll/classifier-reborn/releases) is not tagged here on GitHub yet. Am I being too impatient? ;-)

**Comment by parkr** [comment]
Looks like the `v2.2.0` tag wasn't pushed up?

**Comment by Ch4s3** [comment]
let me take a look

**Comment by Ch4s3** [comment]
Ok, I drafted the release. I thought the jekyll bot would catch it automatically.
