### ISSUE TITLE
Can't include Validator Module

### ISSUE THREAD

**Issue by Carpela** [jekyll/classifier-reborn#167]
require 'classifier-reborn'

include ClassifierReborn::ClassifierValidator
NameError: uninitialized constant ClassifierReborn::ClassifierValidator

Am I doing something stupid here?

**Comment by Carpela** [comment]
Looks like the validators aren't on the 2.1.0 release. 
Pulled the master branch and all working fine.

**Comment by Ch4s3** [comment]
Yeah, sorry @Carpela, I need to roll a new release. I'll either do that soon or update the docs. I'll happily merge a pr.

**Comment by ibnesayeed** [comment]
This can perhaps be closed now.
