### ISSUE TITLE
Update Homepage link on RubyGems site

### ISSUE THREAD

**Issue by ibnesayeed** [jekyll/classifier-reborn#169]
The Homepage link of the [RubyGems site](https://rubygems.org/gems/classifier-reborn) still points to the GitHub repo. Now that we have a [dedicated site for it](http://www.classifier-reborn.com/), I think the link should be updated there.

**Comment by Ch4s3** [comment]
For some reason I can't edit that link. I changed the doc link, but that one I can't.

**Comment by Ch4s3** [comment]
Ahh, I think it pulls from the gemspec which I just updated. I guess we'll have to wait for the next release for this to be reflected on https://rubygems.org/gems/classifier-reborn

**Comment by ibnesayeed** [comment]
I was about to point this out, but I saw you have already committed a change in the gemspec file. :+1:

**Comment by Ch4s3** [comment]
Yep. I'll close this for now then.

**Comment by ibnesayeed** [comment]
@Ch4s3 you might want to add the full URL `http://www.classifier-reborn.com/` instead of just `www.classifier-reborn.com`. Also, the JRuby version of the gemspec may also be changed to keep the metadata in sync, though, I am not sure about that.
