### ISSUE TITLE
Deprecated Gem::Specification#has_rdoc

### ISSUE THREAD

**Issue by mike-stewart** [jekyll/classifier-reborn#181]
I see this error when bundling.

```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from .../classifier-reborn.gemspec:25.
```

Should be a simple change, let me know if you want a PR.

**Comment by mattr-** [comment]
A PR would be great! Thank you! :heart:

**Comment by DirtyF** [comment]
@mike-stewart done, thanks for reporting 👍

**Comment by mike-stewart** [comment]
Thanks! @DirtyF will you be doing a release? Sounds like it could be removed as early as Saturday.

**Comment by DirtyF** [comment]
@mike-stewart prepared a [2.3.0 release](https://github.com/jekyll/classifier-reborn/releases/tag/v2.3.0), all is left is for @parkr or @Ch4s3 to push the gem to rubygems.
