### ISSUE TITLE
2.3.0 not released to Rubygems

### ISSUE THREAD

**Issue by mjc-gh** [jekyll/classifier-reborn#182]
It's committed and available on Github just not released to Rubygems. Thanks for this gem!!

**Comment by Ch4s3** [comment]
Ahh, someone else from jekyll cut a version without telling me, I was planning on adding some needed backwards compat import/export code first. I'll release this later when I'm on the right laptop.

**Comment by khataev** [comment]
Still not released (

**Comment by 0xdevalias** [comment]
Seems [this has still not occured](https://rubygems.org/gems/classifier-reborn/versions/2.2.0), and [makes me think this project may no longer be actively maintained](https://github.com/jekyll/classifier-reborn/issues/193).

**Comment by mattr-** [comment]
The real version 2.3.0 will be out soon. Closing.
