### ISSUE TITLE
broken links to docs (domain name not resolving)

### ISSUE THREAD

**Issue by masukomi** [jekyll/classifier-reborn#183]
the README (and thus front page of github project) has a number of documentation links going to classifier-reborn.com. Unfortunately the domain is in a [clientHold status](https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en#clientHold) which means it isn't resolving and the docs links are broken.

**Comment by a-maas** [comment]
Anyone have any information about this? Is there an alternative place we can find these docs, like a repo for the classifier-reborn website?

**Comment by Ch4s3** [comment]
I'm working on fixing the domain this weekend. For now the docs are in the repo. Sorry for lettignt his slip off my radar, I need to post a request for help maintaining the gem.

**Comment by dltj** [comment]
The domain is resolving again, but the webserver at that domain is returning an HTTP 403 error.

**Comment by tosswill** [comment]
Links are still dead :(

**Comment by Ch4s3** [comment]
Basically someone needs to secure a new domain. Then someone can updated the github page and links. I'll help out if someone wants to take over that. I'm not actively working on this project or Ruby anymore, but I'll happily help someone else get spun up.

**Comment by Ch4s3** [comment]
This is addressed now
