### ISSUE TITLE
Documentation at classifier-reborn.com in inaccessible

### ISSUE THREAD

**Issue by ibnesayeed** [jekyll/classifier-reborn#186]
@Ch4s3 are you still maintaining the `classifier-reborn.com` domain? The site is returning `403 Forbidden` response for quite some time.

**Comment by Ch4s3** [comment]
I didn't have it set to auto renew and lost access to the registrar account where it was originally purchased. Basically it needs to be re-purchased.

**Comment by ibnesayeed** [comment]
A quick fix would be to just rename or remove `docs/CNAME` file (and update links in the README and description of the site) so that at least the site is accessible from the https://jekyll.github.io/classifier-reborn URL. Currently, it is redirecting (`301 Permanently`) to the custom domain which is returning `403 Forbidden`.

```
$ curl -IL https://jekyll.github.io/classifier-reborn/
HTTP/2 301 
server: GitHub.com
content-type: text/html
location: http://www.classifier-reborn.com/
x-github-request-id: 4FEE:0AA2:A6338:D8903:5D8CD1DC
accept-ranges: bytes
date: Thu, 26 Sep 2019 14:57:33 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-dca17768-DCA
x-cache: MISS
x-cache-hits: 0
x-timer: S1569509854.617498,VS0,VE4
vary: Accept-Encoding
x-fastly-request-id: 8d3e87e71d8079e7f2be25b9ad77dadae502f317
content-length: 162

HTTP/1.1 403 Forbidden
Date: Thu, 26 Sep 2019 14:57:33 GMT
Server: Apache/2.4.41 (cPanel) OpenSSL/1.0.2t mod_bwlimited/1.4
Content-Type: text/html; charset=iso-8859-1

```

**Comment by Ch4s3** [comment]
If you open a PR I’ll merge it. I’m traveling and away from my machine so I can’t really do it myself atm.

**Comment by ibnesayeed** [comment]
The `CNAME` file is perhaps generated automatically when a custom domain name is specified on the settings page and the link in the description can be updated from the landing repo page. Once those things are fixed, I can create a PR to update the README.

**Comment by Ch4s3** [comment]
@ibnesayeed done

**Comment by ibnesayeed** [comment]
PR #187 should take care of the rest.
