### ISSUE TITLE
comparison of Float with Float failed (ArgumentError) on a simple training test

### ISSUE THREAD

**Issue by hamac** [jekyll/classifier-reborn#27]
Hi,
I had an error and managed to reproduce it with the following basic test adapted from the Readme example:

``` ruby
require 'classifier-reborn'
lsi = ClassifierReborn::LSI.new
strings = [["Word1 Word2", :cat],
           ["Word1 Word3", :cat],
           ["Word4 Word5 Word6 Word7", :cat]]
strings.each {|x| lsi.add_item x.first, x.last}
```

the third .add_item fails with:

classifier-reborn-2.0.2/lib/classifier-reborn/lsi.rb:284:in `sort': comparison of Float with Float failed (ArgumentError)

Anything I'm doing wrong?

Thanks

**Comment by Ch4s3** [comment]
this is related to #30, so I'm closing in favor of #30
