### ISSUE TITLE
Warning on lsi.rb line 237

### ISSUE THREAD

**Issue by bdthinh** [jekyll/classifier-reborn#34]
Hello guys,

I recently setup lsi for my octopress application but these following warnings always appear and i don't know why:
`/Users/user/.rvm/gems/ruby-2.2.1/gems/classifier-reborn-2.0.3/lib/classifier-reborn/lsi.rb:237: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.`

`/Users/user/.rvm/gems/ruby-2.2.1/gems/classifier-reborn-2.0.3/lib/classifier-reborn/lsi.rb:237: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.`

**Comment by Ch4s3** [comment]
Which version of Jekyll and Octopress are you using? I understand that this issue is sometimes solved by upgrading. If that doesn't fix it, can you provide a bit more info about the input that's causing the spaceship overload warning?

**Comment by bdthinh** [comment]
I'm using Jekyll 2.5.3 and Octopress 2.5 (newest to now, 3.0 is in development). I also try to upgrade Jekyll and Classifier-reborn but nothing's help. The warning is still be there.

**Comment by Ch4s3** [comment]
Can you post the two things being compared that set off the warning? Could you post a full stack trace?

**Comment by parkr** [comment]
I feel like there's a jekyll/jekyll PR for this...

**Comment by Ch4s3** [comment]
@parkr correct: https://github.com/jekyll/jekyll/pull/3629 . So, @bdthinh it looks like you can either: use jekyll head, wait for 3.0, or just ignore the deprecation warning. It doesn't mean anything is wrong per se, just that in future Ruby versions, the <=> will not swallow exceptions from types that aren't comparable. So in future Rubies the input that caused this will throw an exception.

Can we perhaps close this issue unless something else needs to be done?

**Comment by parkr** [comment]
Perhaps the PR on this repo is also aimed toward this?

**Comment by Ch4s3** [comment]
Ahh, correct. #33 is exactly about this as well. I'll take a look and see if I can get that wrapped up.

**Comment by Ch4s3** [comment]
merged #33
