### ISSUE TITLE
How can i pass an array for training words or sentences.

### ISSUE THREAD

**Issue by shilpi230** [jekyll/classifier-reborn#35]
I have some set of arrays containing good and bad words how can i pass into this.  ```classifier.train_interesting```

**Comment by Ch4s3** [comment]
You can just pass in a long string, but if you specifically need to pass in an array you can just iterate.

````ruby
require 'classifier-reborn'

classifier = ClassifierReborn::Bayes.new 'Interesting', 'Uninteresting'
array = ["one", "two", "three"]

array.each do |word|
  classifier.train_interesting word
end
````

**Comment by parkr** [comment]
@Ch4s3 :clap: !
