### ISSUE TITLE
classify_with_score and scored_categories return undefined?

### ISSUE THREAD

**Issue by cheeyeo** [jekyll/classifier-reborn#43]
Hi

I tried running ClassifierReborn::LSI from the example in the README and when invoking the 'classify_with_score' and 'scored_categories' methods, it returns undefined? Am I calling it wrong?

```
lsi = ClassifierReborn::LSI.new

strings = [ ["This text deals with dogs. Dogs.", "a"],
            ["This text involves dogs too. Dogs!", "a"],
            ["This text revolves around cats. Cats.", "b"],
            ["This text also involves cats. Cats!", "b"],
            ["This text involves birds. Birds.", "c"]]

strings.each {|x| lsi.add_item x.first, x.last}

# NoMethodError
scored_categories = lsi.scored_categories("dog bird cat")

# NoMethodError
lsi.classify_with_score("test")
```

**Comment by cheeyeo** [comment]
I also noticed that these methods are not in the gem version pulled from rubygems.org? The LSI class differs from the master branch here in the repo?

**Comment by parkr** [comment]
@cheeyeo the readme might be reflecting current `master` which has (in the last few days) undergone some fairly significant changes. Please use the `master` branch for those or find the readme at the version you're running.

**Comment by cheeyeo** [comment]
@parkr Thanks for the prompt reply! Thought I was losing my mind for a moment :+1:
