### ISSUE TITLE
Diferent weight for known words or user oriented trainning

### ISSUE THREAD

**Issue by jcomello** [jekyll/classifier-reborn#48]
Hi, 
There is a way to add weight for the probabilities? I mean, I have some words that I already know the classifications that they have to be, but I don't know if there's a way to add weights for these words. Thanks

**Comment by Ch4s3** [comment]
You mean manually inserting them into Category's words? There isn't a way to do that at the moment, and it may be out of scope. What do you think @parkr

**Comment by parkr** [comment]
Which classifier is this for? It sounds like you're looking for a way to save and load a model.

**Comment by jcomello** [comment]
I didn't mean add words manually, but add weights to known words. For example:
I know that the word "Cobit" is related to technology, but in a big text it doesn't make much diference. I thought of add some weights for these kind of words. Is it possible?

**Comment by Ch4s3** [comment]
We might be able to do this, but I'm not sure what the best approach would be yet.

**Comment by harlow** [comment]
+1 this would be great addition

**Comment by ggennrich** [comment]
+1 I would really like this feature as well

**Comment by Ch4s3** [comment]
@jcomello @ggennrich or @harlow Anyone still interested in this? I'm open to PRs

**Comment by Ch4s3** [comment]
Closing due to lack of response
