### ISSUE TITLE
Changing language and auto_categorize attributes

### ISSUE THREAD

**Issue by jcomello** [jekyll/classifier-reborn#51]
I have to use the portuguese stopwords at bayes classifier but the initialize method is fixed for english, the auto_categorize has the same issue.

``` ruby
def initialize(*args)
      @categories = Hash.new
      options = { language: 'en', auto_categorize: false }
      ...
end
```

I search at the gem and I didn't find a setter. There is another way?

**Comment by jcomello** [comment]
I found out how to do it.

```ruby
def initialize(*args)
      @categories = Hash.new
      options = { language: 'en', auto_categorize: false }
      args.flatten.each do |arg|
        if arg.kind_of?(Hash)
          options.merge!(arg)
        else
          add_category(arg)
        end
      end
      @total_words = 0
      @category_counts = Hash.new(0)
      @category_word_count = Hash.new(0)
      @language = options[:language]
      @auto_categorize = options[:auto_categorize]
end
```

The initialize method has a decision that merges with the options variable.

I thought about just add some getter and setters, what do you think?

**Comment by Ch4s3** [comment]
we should probably add the ability to set the language with the initialize method and default to English if no language is given.

**Comment by MadBomber** [comment]
```ruby
b = ClassifierReborn::Bayes.new('cat1', 'cat2'. language: 'pi')
```
over-rides the english default; however, I do not see a 'pi' file in the data/stopwords directory.

**Comment by jcomello** [comment]
@MadBomber I figure it out. I just added a new test and attr_reader for language and auto_categorize. I think this is useful.
