### ISSUE TITLE
Feature Reqiest: save/load baysian classifier

### ISSUE THREAD

**Issue by MadBomber** [jekyll/classifier-reborn#53]
Someone mentioned this in a comment within the last rew months.  I thought I'd just consolidate it here.  What I'm thinking about is ClassifierReborn#load and ClassifierReborn#save instance methods that serialize the classifier from/to a compressed file.  It would looking something like this:

```ruby
b = ClassifierReborn.new load: 'path/to/classifier_data.zip'
# and
b = ClassifierReborn.new 'Ham', 'Spam'
b.train :ham, 'good stuff'
b.train :spam, 'processed stuff'
b.save 'path/to/classifier_data.zip'
# or
b.save # to use a default which could be the place from which the serialized data was loaded on initialization
```

**Comment by Ch4s3** [comment]
We can write to `.dat` file with `marshal`, and I can get behind a convenience methods for that. Writing to a zip would require another gem and we try to minimize dependencies. I can take a look at implementing a `.save` though

**Comment by bararchy** [comment]
Do we really need a method for 2 lines of code ? 

```ruby
classifier_snapshot = Marshal.dump @classifier
File.write('path/to/classifier_data.zip', classifier_snapshot)
```

**Comment by Ch4s3** [comment]
@bararchy I'm not really sure. What do you think @parkr?

**Comment by Ch4s3** [comment]
I'll see about putting this in `2.0.5`

**Comment by Ch4s3** [comment]
I'm closing this unless someone else is willing to put in a PR, I'm not sure it is essential to the core of the classifier, but I'm also not opposed to it.

**Comment by MadBomber** [comment]
I'm good with just closing it.
