### ISSUE TITLE
wrong argument type GSL::Vector (expected Data)

### ISSUE THREAD

**Issue by jcomello** [jekyll/classifier-reborn#62]
Hi, I'm having problems using classifier-reborn with GSL and Madeleine Gem.

When there is an madelaine's snapshot I have the error as the following gist

https://gist.github.com/jcomello/3595d8e4db753e1dabc4

Is this a classifier-reborn issue or Madeleine's?

**Comment by Ch4s3** [comment]
Probably Madeline, which has at this point been abandoned. It's probably best to use Marshal at this point, like in the [example](https://github.com/jekyll/classifier-reborn#usage). If the problem persists with Marshal, let me know.

**Comment by Ch4s3** [comment]
@jcomello were you able to resolve this?

**Comment by Ch4s3** [comment]
closing b/c avtivity
