### ISSUE TITLE
Bayes ok for short-form text?

### ISSUE THREAD

**Issue by harlow** [jekyll/classifier-reborn#67]
Forgive me in advance if this is a total noob question.

I've been trying to get Bayes working to categorize job titles. However, i'm running into an issue where the classifier chooses the category with the least training text:

```ruby
#!/usr/bin/env ruby
# classifier_reborn_demo.rb

require 'classifier-reborn'
training_set = DATA.read.split("\n")
categories = training_set.shift.split(',').map{ |c| c.strip }
classifier = ClassifierReborn::Bayes.new categories

training_set.each do |a_line|
  next if a_line.empty? || '#' == a_line.strip[0]
  parts = a_line.strip.split(':')
  classifier.train(parts.first, parts.last)
end

puts classifier.classify "Regional Marketing Assistant"

__END__
Consulting,Marketing
# consulting titles
consulting: Consultant
consulting: Consulting
# marketing titles
marketing: Chief Marketing Officer
marketing: Marketing
marketing: Marketing Operations
marketing: Search Engine Optimization
marketing: SEO
```

The classifier is returning `consulting` even though Marketing appears in the title.

```
ruby scripts/classifier_reborn_demo.rb
Consulting
-10.239959789157341
```

It's possible Bayes it not suited for this type of classification? Maybe bag-of-words algo might be better suited for this type of classification? 

Thanks in advance!

**Comment by Ch4s3** [comment]
Since Bayes works off of prior probability, you sample size of priors will influence classification. Is this all of the data you're training with?

**Comment by harlow** [comment]
I have a list of around 150 titles -- Seems that removing the less frequent nodes like "consulting" pushes the match to the next classification w/ least occurrences.

**Comment by Ch4s3** [comment]
That sounds like what I would expect. To be super easy to use and generalizable, classifier-reborn takes a somewhat naive approach to bayes, so you might have to experiment to get the best results. I've found through personal use that testing the results and adding more data usually works well.

I'm going to keep this issue open for now, and if you have more issues we'll dig in to see if something is off.

**Comment by Ch4s3** [comment]
Since it has been 3 months, I'm closing the issue pending future issues.
