### ISSUE TITLE
Marshal data too short

### ISSUE THREAD

**Issue by marciovicente** [jekyll/classifier-reborn#70]
I've installed all dependencies (rb-gsl, gsl, classifier-reborn) and when I try load the my trained LSI data model i get this error: `Marshal data too short`

So I've checked the model and it's seems ok.

The code below work fine in my personal computer (Mac OS 10.11) but when I'm trying to run it in my webserver (Ubuntu 15.10) this doesn't work. Is there any problem generate this model in an OSX computer and try to use the classify in another OS? Maybe GSL lib version or something like this.

```ruby
require 'classifier-reborn'

model = File.read("#{Rails.root}/bin/lsi-model.dat")
lsi_classifier = Marshal.load(model)
```

**Comment by Ch4s3** [comment]
Hum. This might be an issue with Marshal. Can you post more code/data to reproduce this?

**Comment by Ch4s3** [comment]
@marciovicente are you still having this issue?

**Comment by marciovicente** [comment]
I don't know exactly what's happened, but this bug doesn't reproduce anymore, so I'll close this issue. Thx!

**Comment by Ch4s3** [comment]
Good to hear. I suspect it was an interaction between Marshal and something else on the OS, I could never reproduce it.
