### ISSUE TITLE
Functionality to modify stopword lists?

### ISSUE THREAD

**Issue by chris357** [jekyll/classifier-reborn#72]
What is the current recommended practise for modifying stopwords. Just edit the word out of the list?

Currently, `not` is a stopword in English.

But it would be beneficial in my use-cases if `not` was not a stopword. In order to distinguish strings like below. 
```
"This is a dog." => :dog
"This is not a dog."=> :otherAnimal
```
In which case `not` might have an impact.

Thoughts?

**Comment by Ch4s3** [comment]
Check out this [line, hasher.rb#L27]( https://github.com/jekyll/classifier-reborn/blob/014881c61070cf061e27ec1c94b8444702c59feb/lib/classifier-reborn/extensions/hasher.rb#L27). It defaults to "en", but you can set it to another language. That language file could be english-not or whatever. Right now we don't have great functionality for loading arbitrary  language file. If you wanted to put in a simple PR to do that I'd take a look.
