### ISSUE TITLE
Using Redis for the data structure

### ISSUE THREAD

**Issue by ibnesayeed** [jekyll/classifier-reborn#81]
I have seen references to Redis in the README for dumping and restoring the complete marshaled snapshot. This, in my opinion, has very little advantage over storing the data in a file.

However, using Redis for storing individual counter objects/hashes (with some name-spacing in place) rather than using raw memory would be a nice feature. Every time a counter needs to be updated for training, it will update necessary records on Redis and when classify method is called, it will pull the vectors from Redis. This approach will have following advantages:

* in case of accidental program crash the training data will not be lost
* a shared Redis store instance with adequate memory can serve many small worker application instances that can participate in training and classifying documents

Possible approach to implement it:

* define proxy methods to override `[]` and `[]=` in a way that can save and retrieve records to and from Redis the same way it would with a hash
* in the `initialize` method check to see if Redis configs are supplied, only then override the hash accessors, this way the classifier would seamlessly work with and without Redis while avoiding branching (conditional check) on each read and write operation

Thoughts?

**Comment by Ch4s3** [comment]
That sounds pretty compelling. I'd be happy to look at a pr.

**Comment by ibnesayeed** [comment]
I will try to give it a shot. However, looking at the code in `bayes.rb`, I feel that it would be a lot easier and quicker to abstract out the certain portions of `train`, `untrain` and `classifications` methods as separate private methods and conditionally alias them (during initialization) for their corresponding Redis implementations. I earlier proposed overriding `[]` and `[]=` methods, but after looking at the actual code, I think that would be too complected and unnecessary.

**Comment by parkr** [comment]
Yeah, one common idiom is to create backends. So you have a MemoryBackend, a RedisBackend, and so forth. They all share a common interface but are separate so you can worry about one at a time.

**Comment by ibnesayeed** [comment]
> @parkr: Yeah, one common idiom is to create backends. So you have a MemoryBackend, a RedisBackend, and so forth. They all share a common interface but are separate so you can worry about one at a time.

I tried using this backend approach you suggested. Currently, it only supports the Memory backend, but the refactoring I did establishes the foundation and uniform API for other backends. Please find the changes in PR #84. I would really appreciate any code reviews and comments. I would note that I touched some Ruby code after a long time.

**Comment by ibnesayeed** [comment]
Redis backend implementation is done (except code review and documentation). How about MongoDB, SQLite, MySQL, and/or PostgreSQL backends? Because Redis, though persistent, is still memory based and would require a lot of memory for bigger datasets.

**Comment by Ch4s3** [comment]
Hum. I'd say we might want to wait until we have some users that want to use a database backend. We have a pretty small number of contributors, so I don't like to add a lot of things that have to be maintained unless they're going to get used.

**Comment by ibnesayeed** [comment]
Closing this as this is now implemented by #84.
