### ISSUE TITLE
Unnecessary intermediate variables

### ISSUE THREAD

**Issue by ibnesayeed** [jekyll/classifier-reborn#89]
I was casually looking at the code and found a few places where method arguments were assigned to another intermediate variable while there was no need to preserve the original argument.

* [word_list.rb#L16](https://github.com/jekyll/classifier-reborn/blob/aac50ead9f6c86c336031e86e929a16f07548d65/lib/classifier-reborn/lsi/word_list.rb#L16)
* [word_list.rb#L22](https://github.com/jekyll/classifier-reborn/blob/aac50ead9f6c86c336031e86e929a16f07548d65/lib/classifier-reborn/lsi/word_list.rb#L22)

If this is part of some style then why the same is not practiced in [word_list.rb#L26](https://github.com/jekyll/classifier-reborn/blob/aac50ead9f6c86c336031e86e929a16f07548d65/lib/classifier-reborn/lsi/word_list.rb#L26)?

**Comment by Ch4s3** [comment]
Thanks!
