### ISSUE TITLE
Remove /bin file cruft

### ISSUE THREAD

**Issue by Ch4s3** [jekyll/classifier-reborn#94]
Does anyone actually use the setup in the files here https://github.com/jekyll/classifier-reborn/tree/master/bin?

They're setup is quite outdated, and I don't know what summarize is. Does anyone use them? If not I'm removing `summarize.rb` and cutting the setup from the other file as part of the path towards `3.0`. Thoughts @parkr?

**Comment by bararchy** [comment]
Never used them :)

**Comment by pathawks** [comment]
I was wondering why they were added, so I went looking for that PR. Turns out they have existed since the very first commit of **Classifier**

8cd11c0ef3406a5bb3170de06e8744d75db49931

**Comment by Ch4s3** [comment]
Yeah, i think Lucas was using it to provide either some smoke testing functionality, or may have intended to build a command line parser into the thing.

**Comment by parkr** [comment]
I think they were previously used for testing. I think they're safe to remove.

I think an executable could be an interesting addition for users of persistent datastores. The new Redis backend, for example, could enable this library to be used against a much larger dataset than can fit in process memory. An executable could be used to train and classify inputs for systems using persistent datastores.

**Comment by Ch4s3** [comment]
> an executable could be an interesting addition for users of persistent datastores

Yeah that would be interesting. I'll make a new issue about investigating that.
